ALBUMS

### Get all albums
GET http://localhost:3000/albums

### Get album by id for 1 album 
GET http://localhost:3000/albums/663e687bce3ea8b2cb19048e

### Create album
POST http://localhost:3000/albums  HTTP/1.1
Content-Type: application/json

{
    "name": "1989 (Taylor's Version)",
    "artist": "Taylor Swift",
    "songsNumber": 22,
    "link": "https://open.spotify.com/album/64LU4c1nfjz1t4VnGhagcg?si=c_dOxJNMQYWAZTFrmZUAEw",
    "releaseDate": "27.10.2023",
    "genre": "Pop",
    "labelName": "EMI"
}

### Update album
PUT http://localhost:3000/albums/663e687bce3ea8b2cb198e HTTP/1.1
Content-Type: application/json

{
    "name": "2003 (Taylor's Version)",
    "artist": "a",
    "songsNumber": 0,
    "link": "https://open.spotify.com/album/64LU4c1nfjz1t4VnGhagcg?si=c_dOxJNMQYWAZTFrmZUAEw",
    "releaseDate": "27.10.2023",
    "genre": "Rock",
    "labelName": "EMI"
}

### Delete album
DELETE http://localhost:3000/albums/663e687bce3ea8b2cb19048e HTTP/1.1





BOOKS

### Get all books
GET http://localhost:3000/books

### Get album by id for 1 album 
GET http://localhost:3000/books/663d214be73d416a1d89fd42

### Create album
POST http://localhost:3000/books  HTTP/1.1
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "isbn": "9780743273565",
  "language": "English",
  "pages": 180,
  "publishedYear": 1925
}

### Update album
PUT http://localhost:3000/books/663e80cc9c29e92b06e0223 HTTP/1.1
Content-Type: application/json

{
  "title": "The Small Gatsby",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "isbn": "9780743273565",
  "language": "English",
  "pages": 180,
  "publishedYear": 1925
}

### Delete album
DELETE http://localhost:3000/books/663e7eae9c29e92b06e02237 HTTP/1.1
