ALBUMS

### Get all albums
GET http://localhost:3000/albums

### Get album by id for 1 album 
GET http://localhost:3000/albums/6633d477a5f295c21c85f

### Create album
POST http://localhost:3000/albums  HTTP/1.1
Content-Type: application/json

{
    "name": "1989 (Taylor's Version)",
    "artist": "Taylor Swift",
    "songsNumber": 22,
    "link": "https://open.spotify.com/album/64LU4c1nfjz1t4VnGhagcg?si=c_dOxJNMQYWAZTFrmZUAEw",
    "releaseDate": "27.10.2023",
    "genre": "Pop",
    "labelName": "EM"
}

### Update album
PUT http://localhost:3000/albums/663d1ed7e73d416a1d89fd41 HTTP/1.1
Content-Type: application/json

{
    "name": "2003 (Taylor's Version)",
    "artist": "Taylor Swift",
    "songsNumber": 22,
    "link": "https://open.spotify.com/album/64LU4c1nfjz1t4VnGhagcg?si=c_dOxJNMQYWAZTFrmZUAEw",
    "releaseDate": "27.10.2023",
    "genre": "Pop",
    "labelName": "E"
}

### Delete album
DELETE http://localhost:3000/albums/663d2150e73d416a1d89fd43 HTTP/1.1





BOOKS

### Get all books
GET http://localhost:3000/books

### Get album by id for 1 album 
GET http://localhost:3000/books/663bc82577a5f2995c21c86b

### Create album
POST http://localhost:3000/books  HTTP/1.1
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "isbn": "9780743273565",
  "language": "English",
  "pages": 180,
  "publishedYear": 1925
}

### Update album
PUT http://localhost:3000/books/663bd9f97f5b72c5b55d49b2 HTTP/1.1
Content-Type: application/json

{
  "title": "The Small Gatsby",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "isbn": "9780743273565",
  "language": "English",
  "pages": 180,
  "publishedYear": 1925
}

### Delete album
DELETE http://localhost:3000/books/663bd9f97f5b72c5b55d49b2 HTTP/1.1
